name: deploy-container #workflow name

on: #designate event will be trigger
  push: #push event
    branches: #on branch
      - dev #watching pushing event on branch master
    paths:
      - "packages/container/**" #watching changes on this path

default:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-lastest #create linux virtual env

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ""
